relative_permalinks: false

# Site settings
title:       rob gillen
email:       rob+blog@gillenfamily.net
author:      Rob Gillen
tagline:          'random wanderings through technology, code and life'
description:      '<img src="/images/621404.jpg" style="width:230px;height:230px;"> Rob Gillen<br>Senior Research Professional<br/> Oak Ridge National Laboratory'
baseurl:     ""
url:         "http://robgillen.com"

# Google analytics
google_analytics: UA-387099-5

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  true

# configure the highlighter
highlighter: rouge

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: false
github_username: argodev
stackoverflow_id: argodev
twitter_username: argodev
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false

# Build settings
safe: false
future:      true
markdown:     kramdown
permalink:    pretty
paginate:     5
paginate_path: "/page:num"
excerpt_separator: <!--more-->
sass:
  compressed: true

gems:
  - jekyll-redirect-from
  - jekyll-paginate
  - jemoji
  - font-awesome-sass
  - kramdown
  - rouge

# About/contact
author:
  name:              Rob Gillen
  url:               https://twitter.com/argodev
  avatar:         foo.png
  #email:


# Owner/author information
owner:
  name:           Rob Gillen
  avatar:         foo.png
  #email:
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:
  # Social networking links used in footer. Update and remove as you like.
  twitter:        argodev
  facebook:
  github:         argodev
  stackexchange:
  linkedin:       https://www.linkedin.com/in/foo
  instagram:
  flickr:
  tumblr:
  google_plus:    https://plus.google.com/+foo
  # orcid and google scholar IDs are different than standard username.
  orcid: 0000-0002-9002-1440
  gscholar: xyz123abc

## sidebar links:
# For external links add external: true
links:
  - title: <i class="iconside iconm-home"></i> Home
    url: /
  - title: <i class="iconside iconm-user"></i> About
    url: /about/
  - title: <i class="iconside iconm-quill"></i> Blog
    url: /blog/
  - title: <i class="fa fa-tags"></i> Tags
    url: /tags/
  - title: <i class="fa fa-archive"></i> Archive
    url: /archive/
  - title: <i class="iconside iconm-bullhorn"></i> Presentations
    url: /presentations/
  - title: <i class="iconside iconm-envelop"></i> Contact
    url: /contact/
  - title: <i class="iconside iconm-twitter"></i> Twitter
    url: https://twitter.com/argodev
    external: true
  - title: <i class="iconside iconm-feed2"></i> Feed
    url: /feed.xml
  - title: <i class=""></i> Disclosure
    url: /disclosure

# Google Custom Search:
google_search: 003285320253376666153:uitdowlq-os

# Twitter stream widget:
# Replace xyz123abc with your twitter widget id from https://twitter.com/settings/widgets
twitter_widget_id: 757763240646500354

# Add disqus username for Disqus comment board:
disqus_shortname: foo

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-387099-5

#### For dummy website only - remove if you wish ####
#github_repo: https://github.com/dyndna/lanyon-plus
#version: 1.1.0
## END ##
