# Site settings
title:       rob gillen
email:       rob+blog@gillenfamily.net
author:      Rob Gillen
tagline:          'random wanderings through technology, code and life'
description:      '<img src="/images/621404.jpg" style="width:230px;height:230px;"> Rob Gillen<br>Senior Research Professional<br/> Oak Ridge National Laboratory'
baseurl:     ""
url:         "http://robgillen.com"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  true

# configure the highlighter
highlighter: rouge

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: false
github_username: argodev
stackoverflow_id: argodev
twitter_username: argodev
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true

gems:
  - jekyll-redirect-from
  - jekyll-paginate
