# Site settings
title:       rob gillen
email:       rob+blog@gillenfamily.net
author:      Rob Gillen
description: "random wanderings through code and life"
baseurl:     ""
url:         "http://robgillen.com"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: rgillen

# Social icons
show_social_icons: false
github_username: argodev
stackoverflow_id:
twitter_username: argodev
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true

gems:
  - jekyll-redirect-from

