# Dependencies
markdown:         redcarpet
# pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            rob gillen
tagline:          'random wanderings through code and life'
description:      'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://robgillen.com

author:
  name:           'Rob Gillen'
  url:            https://twitter.com/argodev

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/argodev/argodev.github.io

gems:
  - jekyll-redirect-from
  - jekyll-paginate
